# Q3 sandbox

The database has two schemas, recreated every time you run `docker compose up`:

| Schema | Contents |
|---|---|
| `edge_cases` | 15 users, one per edge case (see `app/data.py`) |
| `full_data` | the edge cases + 5,000 random users |

All dates are relative to **yesterday (UTC)** when the data was loaded.

- `%%sql` cells run SQL directly. Switch schema with `SET search_path TO full_data;`
- `run_query("q3a")` runs a query file from `queries/` and returns a DataFrame.

In [10]:
import os
from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql+psycopg://postgres:postgres@localhost:55432/q3")
QUERIES_DIR = Path(os.environ.get("QUERIES_DIR", "/queries"))

engine = create_engine(DATABASE_URL, connect_args={"options": "-c search_path=edge_cases -c timezone=UTC"})

%load_ext sql
%sql engine
%config SqlMagic.displaylimit = 100

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

## Explore the data

In [11]:
%%sql
SELECT subscription_id, user_id, product, start_date, end_date
FROM subscriptions
ORDER BY user_id, subscription_id

Running query in 'postgresql+psycopg://postgres:***@db:5432/q3'

21 rows affected.

+-----------------+-----------------------+---------+------------+------------+
| subscription_id |        user_id        | product | start_date |  end_date  |
+-----------------+-----------------------+---------+------------+------------+
|        3        |    u_both_products    |   pro   | 2026-08-25 |    None    |
|        4        |    u_both_products    |    mp   | 2026-09-14 |    None    |
|        15       |    u_cross_product    |    mp   | 2026-08-05 |    None    |
|        16       |    u_cross_product    |   pro   | 2026-09-24 | 2026-09-29 |
|        9        |    u_duplicate_pro    |   pro   | 2026-08-25 |    None    |
|        10       |    u_duplicate_pro    |   pro   | 2026-09-24 | 2026-10-10 |
|        21       | u_ended_before_window |   pro   | 2026-06-26 | 2026-08-15 |
|        2        |    u_ends_yesterday   |   pro   | 2026-08-05 | 2026-10-04 |
|        20       |        u_future       |   pro   | 2026-10-09 |    None    |
|        13       |       u_inverted      |   pro   | 2026-09-24 | 2026-08-25 |
|        14       |      u_null_start     |   pro   |    None    |    None    |
|        6        |   u_paying_no_events  |   pro   | 2026-08-25 |    None    |
|        1        |       u_pro_open      |   pro   | 2026-08-25 |    None    |
|        7        |       u_renewal       |   pro   | 2026-03-18 | 2026-06-26 |
|        8        |       u_renewal       |   pro   | 2026-06-26 |    None    |
|        5        |   u_starts_yesterday  |    mp   | 2026-10-04 |    None    |
|        17       |      u_three_way      |   pro   | 2026-08-15 |    None    |
|        18       |      u_three_way      |   pro   | 2026-09-04 | 2026-10-03 |
|        19       |      u_three_way      |    mp   | 2026-09-14 | 2026-10-14 |
|        11       |     u_zero_length     |   pro   | 2026-09-14 | 2026-09-14 |
|        12       |     u_zero_length     |    mp   | 2026-09-09 |    None    |
+-----------------+-----------------------+---------+------------+------------+

In [12]:
%%sql
SELECT event_ts, user_id, event_name
FROM events
ORDER BY event_ts

Running query in 'postgresql+psycopg://postgres:***@db:5432/q3'

22 rows affected.

+---------------------+-----------------------+------------+
|       event_ts      |        user_id        | event_name |
+---------------------+-----------------------+------------+
| 2026-09-04 23:59:59 |       u_pro_open      |    view    |
| 2026-09-05 00:00:00 |       u_pro_open      |    view    |
| 2026-09-14 10:00:00 |     u_zero_length     |    view    |
| 2026-09-19 10:00:00 |       u_inverted      |    view    |
| 2026-09-27 10:00:00 |    u_cross_product    |    view    |
| 2026-09-29 10:00:00 |       u_renewal       |    view    |
| 2026-10-01 10:00:00 | u_ended_before_window |    view    |
| 2026-10-02 10:00:00 |      u_three_way      |    view    |
| 2026-10-02 10:00:00 |      u_null_start     |    view    |
| 2026-10-03 09:00:00 |    u_ends_yesterday   |    view    |
| 2026-10-03 13:00:00 |          None         |    view    |
| 2026-10-04 00:00:00 |   u_starts_yesterday  |    view    |
| 2026-10-04 08:00:00 |    u_duplicate_pro    |    view    |
| 2026-10-04 09:00:00 |    u_ends_yesterday   |    view    |
| 2026-10-04 10:00:00 |       u_pro_open      |    view    |
| 2026-10-04 10:00:00 |        u_future       |    view    |
| 2026-10-04 12:00:00 |    u_both_products    |    view    |
| 2026-10-04 13:00:00 |          None         |    view    |
| 2026-10-04 14:00:00 |        u_orphan       |    view    |
| 2026-10-04 15:00:00 |   u_no_subscription   |    view    |
| 2026-10-04 23:59:59 |    u_duplicate_pro    |    view    |
| 2026-10-05 00:00:00 |       u_pro_open      |    view    |
+---------------------+-----------------------+------------+

## Run the Q3 query files

In [13]:
def run_query(name: str, schema: str = "edge_cases") -> pd.DataFrame:
    """Run queries/<name>.sql against a schema and return the result."""
    sql = (QUERIES_DIR / f"{name}.sql").read_text()
    with engine.connect() as conn:
        conn.exec_driver_sql(f"SET search_path TO {schema}")
        result = conn.exec_driver_sql(sql)
        return pd.DataFrame(result.fetchall(), columns=list(result.keys()))


run_query("q3a")

,activity_date,paying_active_users,pro_paying_active_users,mp_paying_active_users
0,2026-09-05,1,1,0
1,2026-09-06,0,0,0
2,2026-09-07,0,0,0
3,2026-09-08,0,0,0
4,2026-09-09,0,0,0
5,2026-09-10,0,0,0
6,2026-09-11,0,0,0
7,2026-09-12,0,0,0
8,2026-09-13,0,0,0
9,2026-09-14,1,0,1
10,2026-09-15,0,0,0
11,2026-09-16,0,0,0
12,2026-09-17,0,0,0
13,2026-09-18,0,0,0
14,2026-09-19,0,0,0
15,2026-09-20,0,0,0
16,2026-09-21,0,0,0
17,2026-09-22,0,0,0
18,2026-09-23,0,0,0
19,2026-09-24,0,0,0
20,2026-09-25,0,0,0
21,2026-09-26,0,0,0
22,2026-09-27,1,1,1
23,2026-09-28,0,0,0
24,2026-09-29,1,1,0
25,2026-09-30,0,0,0
26,2026-10-01,0,0,0
27,2026-10-02,1,1,1
28,2026-10-03,1,1,0
29,2026-10-04,4,3,2

In [5]:
run_query("q3b")

   activity_date  active_users  paying_active_users pct_paying
0     2026-09-05             1                    1     100.00
1     2026-09-06             0                    0       None
2     2026-09-07             0                    0       None
3     2026-09-08             0                    0       None
4     2026-09-09             0                    0       None
5     2026-09-10             0                    0       None
6     2026-09-11             0                    0       None
7     2026-09-12             0                    0       None
8     2026-09-13             0                    0       None
9     2026-09-14             1                    1     100.00
10    2026-09-15             0                    0       None
11    2026-09-16             0                    0       None
12    2026-09-17             0                    0       None
13    2026-09-18             0                    0       None
14    2026-09-19             1                    0       0.00
15    2026-09-20             0                    0       None
16    2026-09-21             0                    0       None
17    2026-09-22             0                    0       None
18    2026-09-23             0                    0       None
19    2026-09-24             0                    0       None
20    2026-09-25             0                    0       None
21    2026-09-26             0                    0       None
22    2026-09-27             1                    1     100.00
23    2026-09-28             0                    0       None
24    2026-09-29             1                    1     100.00
25    2026-09-30             0                    0       None
26    2026-10-01             1                    0       0.00
27    2026-10-02             2                    1      50.00
28    2026-10-03             1                    1     100.00
29    2026-10-04             8                    4      50.00

In [6]:
run_query("q3c")

,user_id,subscription_id_1,product_1,start_date_1,end_date_1,subscription_id_2,product_2,start_date_2,end_date_2,same_product,overlap_start,overlap_end
0,u_both_products,3,pro,2026-08-25,None,4,mp,2026-09-14,None,False,2026-09-14,None
1,u_cross_product,15,mp,2026-08-05,None,16,pro,2026-09-24,2026-09-29,False,2026-09-24,2026-09-29
2,u_duplicate_pro,9,pro,2026-08-25,None,10,pro,2026-09-24,2026-10-10,True,2026-09-24,2026-10-10
3,u_three_way,17,pro,2026-08-15,None,18,pro,2026-09-04,2026-10-03,True,2026-09-04,2026-10-03
4,u_three_way,17,pro,2026-08-15,None,19,mp,2026-09-14,2026-10-14,False,2026-09-14,2026-10-14
5,u_three_way,18,pro,2026-09-04,2026-10-03,19,mp,2026-09-14,2026-10-14,False,2026-09-14,2026-10-03

In [7]:
# the same queries on the bigger random dataset
run_query("q3a", schema="full_data")

,activity_date,paying_active_users,pro_paying_active_users,mp_paying_active_users
0,2026-09-05,600,348,349
1,2026-09-06,579,348,326
2,2026-09-07,613,344,376
3,2026-09-08,614,351,376
4,2026-09-09,606,358,358
5,2026-09-10,593,373,324
6,2026-09-11,630,359,384
7,2026-09-12,623,373,355
8,2026-09-13,623,353,378
9,2026-09-14,634,380,356
10,2026-09-15,605,356,360
11,2026-09-16,601,367,344
12,2026-09-17,625,363,387
13,2026-09-18,603,362,350
14,2026-09-19,601,351,377
15,2026-09-20,672,398,415
16,2026-09-21,623,369,376
17,2026-09-22,669,402,389
18,2026-09-23,666,377,409
19,2026-09-24,635,383,382
20,2026-09-25,659,390,398
21,2026-09-26,657,403,397
22,2026-09-27,633,373,392
23,2026-09-28,666,394,399
24,2026-09-29,643,389,389
25,2026-09-30,650,404,382
26,2026-10-01,673,392,413
27,2026-10-02,635,379,385
28,2026-10-03,672,400,416
29,2026-10-04,666,399,411

In [ ]:
# overlap detection on the bigger random dataset
run_query("q3c", schema="full_data").head(20)

## Your own SQL

An example: look at one edge case end to end. Note: `SET search_path` in a `%%sql` cell stays in effect for later `%%sql` cells.

In [8]:
%%sql
SELECT s.subscription_id, s.product, s.start_date, s.end_date, e.event_ts
FROM subscriptions s
LEFT JOIN events e ON e.user_id = s.user_id
WHERE s.user_id = 'u_three_way'
ORDER BY s.subscription_id, e.event_ts

Running query in 'postgresql+psycopg://postgres:***@db:5432/q3'

3 rows affected.

+-----------------+---------+------------+------------+---------------------+
| subscription_id | product | start_date |  end_date  |       event_ts      |
+-----------------+---------+------------+------------+---------------------+
|        17       |   pro   | 2026-08-15 |    None    | 2026-10-02 10:00:00 |
|        18       |   pro   | 2026-09-04 | 2026-10-03 | 2026-10-02 10:00:00 |
|        19       |    mp   | 2026-09-14 | 2026-10-14 | 2026-10-02 10:00:00 |
+-----------------+---------+------------+------------+---------------------+

In [9]:
%%sql
SET search_path TO full_data;
SELECT product, count(*) AS subscriptions
FROM subscriptions
GROUP BY product

Running query in 'postgresql+psycopg://postgres:***@db:5432/q3'

2 rows affected.

+---------+---------------+
| product | subscriptions |
+---------+---------------+
|   pro   |      2949     |
|    mp   |      3041     |
+---------+---------------+